import Link from "next/link";
import { LeadForm } from "../_components/LeadForm";
import { Arrow, PageIntro } from "../_components/SiteChrome";
import { pageMetadata } from "../_data/metadata";

export const metadata = pageMetadata({ title: "Horalix Investor Overview", description: "Horalix investor overview: the echo-lab workflow problem, product approach, responsible clinical-AI thesis, milestones, and private materials request.", path: "/investors" });

export default function Investors() {
  return <>
    <PageIntro eyebrow="Investor overview" title="Build the trusted workflow layer for AI-assisted echo." copy="Horalix is developing an echo-first, review-led product for the space between DICOM acquisition and report-ready output." actions={<><a className="button button-light" href="#access">Request investor materials <Arrow /></a><Link className="button button-ghost" href="/platform">Explore the product</Link></>} />
    <section className="section shell"><div className="grid-2"><div><p className="eyebrow">The problem</p><h2>Echo interpretation carries repetitive preparation around high-value judgment.</h2></div><div><p className="lede">Manual measurement and reporting steps can fragment attention and make workflow consistency difficult. The opportunity is not to remove clinical judgment—it is to prepare a clearer, structured review surface around it.</p><div className="disclosure"><strong>Investor disclosure:</strong> Horalix is pilot-stage and pre-clearance. This page contains no financial projections, fundraising terms, or unsupported market-size figures.</div></div></div></section>
    <section className="section section-dark"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Why this approach</p><h2>Focus creates a more credible path to evidence.</h2></div><p className="lede">Echo-first scope, workflow context, clinician control, and claim governance reinforce one another.</p></div><div className="grid-3"><div className="metricless-card"><b>Focus</b><p>A deliberately bounded initial modality and workflow.</p></div><div className="metricless-card"><b>Defensibility</b><p>Product learning spans image understanding, structured output, integration, review behavior, and evidence operations.</p></div><div className="metricless-card"><b>Trust</b><p>Claims, product status, and limitations are governed as part of the product—not polished later.</p></div></div></div></section>
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Milestones</p><h2>Show verified progress, not vanity proof.</h2></div><p className="lede">Named partners, programs, pilots, and performance milestones are supplied in private materials only after evidence and brand-use approval.</p></div><div className="timeline"><div className="timeline-row"><b>Product</b><div><h3>Echo-first workflow development</h3><p>Connect eligible DICOM study intake, structured assistance, contextual review, and report-ready preparation.</p></div></div><div className="timeline-row"><b>Clinical</b><div><h3>Versioned validation pathway</h3><p>Define intended workflow, limitations, benchmark protocol, user evaluation, and site-specific pilot measures.</p></div></div><div className="timeline-row"><b>Company</b><div><h3>Evidence-gated market development</h3><p>Build qualified hospital and investor relationships without publishing unverified logos or headline metrics.</p></div></div></div></section>
    <section className="section section-blue"><div className="shell grid-2"><div><p className="eyebrow">Why now</p><h2>Clinical AI is moving from model fascination to deployment discipline.</h2></div><p className="lede">Hospitals increasingly need evidence, integration, human factors, governance, and economic value to align. Horalix is being built for that more demanding buying environment.</p></div></section>
    <section className="section shell" id="access"><div className="form-section"><div><p className="eyebrow">Private follow-up</p><h2>Request the investor overview.</h2><p className="lede">Qualified investors can request current company materials, verified milestones, and a focused conversation with the team.</p><p className="microcopy">No public fundraising terms, projections, or unsupported TAM figures are presented on this website.</p></div><div className="form-card"><h3>Request investor materials</h3><p>Tell us who you are and what you would like to understand.</p><LeadForm intent="investor_access" /></div></div></section>
  </>;
}
