import type { Metadata } from "next";
import Link from "next/link";
import { ProductFrame } from "../_components/ProductFrame";
import { Arrow, PageIntro, SplitCta } from "../_components/SiteChrome";

export const metadata: Metadata = { title: "AI-assisted echocardiography platform", description: "Explore Horalix: a DICOM echocardiography workflow for structured measurements, contextual overlays, and clinician-controlled review.", alternates: { canonical: "/platform" } };

const software = { "@context": "https://schema.org", "@type": "SoftwareApplication", "@id": "https://horalix.com/platform#software", name: "Horalix", applicationCategory: "HealthApplication", operatingSystem: "Web", description: "Pilot-stage AI-assisted echocardiography workflow for clinician review.", publisher: { "@id": "https://horalix.com/#organization" }, url: "https://horalix.com/platform", offers: { "@type": "Offer", availability: "https://schema.org/LimitedAvailability" } };

export default function Platform() {
  return <>
    <PageIntro eyebrow="The Horalix platform" title="One workspace between the echo study and sign-off." copy="Horalix prepares structured measurements and overlays from DICOM echocardiography studies, then keeps the clinician in control of every review decision." actions={<><Link className="button button-light" href="/for-hospitals#request">Request hospital demo <Arrow /></Link><Link className="button button-ghost" href="/product-tour">Watch product tour</Link></>} />
    <section className="section shell"><ProductFrame /></section>
    <section className="section-tight shell"><div className="feature-stack">
      <article className="feature-block"><div className="feature-copy"><p className="eyebrow">01 · Study intake</p><h2>Meet the study where the workflow begins.</h2><p>Horalix is designed around DICOM echocardiography inputs, with routing and source-system compatibility confirmed during pilot scoping.</p><ul className="feature-list"><li>Scoped DICOM workflow</li><li>Eligible-study routing</li><li>Visible unsupported-study handling</li></ul></div><div className="feature-visual"><div className="metricless-card"><b>Study context</b><p>Source views, study metadata, and workflow status stay connected.</p></div></div></article>
      <article className="feature-block"><div className="feature-copy"><p className="eyebrow">02 · AI assistance</p><h2>Organize outputs around the image.</h2><p>Suggested measurements and overlays appear with the view that produced them, helping reviewers judge the output in context.</p><ul className="feature-list"><li>View-linked measurements</li><li>Visual overlays</li><li>Clear unavailable-result states</li></ul></div><div className="feature-visual"><svg viewBox="0 0 440 300" aria-hidden="true"><path d="M220 20C155 90 70 190 40 280h360C370 190 285 90 220 20Z" fill="#102231"/><path d="M137 238c28-82 58-128 84-150 35 29 68 90 84 150-63-29-111-28-168 0Z" fill="none" stroke="#42d6c8" strokeWidth="3"/><path d="M156 226h133M220 88v166" stroke="#1e5eff" strokeWidth="2" strokeDasharray="7 7"/></svg></div></article>
      <article className="feature-block"><div className="feature-copy"><p className="eyebrow">03 · Clinician review</p><h2>Make disagreement easy.</h2><p>The intended workflow lets clinicians inspect, adjust, accept, or reject suggestions before preparing report-ready outputs.</p><ul className="feature-list"><li>Explicit review status</li><li>Editable suggestions</li><li>Clinician sign-off retained</li></ul></div><div className="feature-visual"><div className="metricless-card"><b>Final control</b><p>AI assistance remains subordinate to clinical judgment throughout review.</p></div></div></article>
    </div></section>
    <section className="quote-band"><div className="shell"><blockquote>Designed to reduce repetitive preparation—not the clinician’s responsibility to interpret the study.</blockquote></div></section>
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Product status</p><h2>Built for transparent evaluation.</h2></div><p className="lede">Horalix is pilot-stage and pre-clearance. It is not presented as independently diagnostic or cleared for routine clinical use.</p></div><div className="metricless-grid"><div className="metricless-card"><b>Scope</b><p>Echo-first product development keeps the workflow and evidence boundary clear.</p></div><div className="metricless-card"><b>Validation</b><p>Product claims are separated from field literature and tied to a version.</p></div><div className="metricless-card"><b>Oversight</b><p>Outputs require review and clinician sign-off.</p></div></div></section>
    <SplitCta /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(software) }} />
  </>;
}
