import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, PageIntro, SplitCta } from "../_components/SiteChrome";

export const metadata: Metadata = { title: "About", description: "Horalix is building an echo-first clinical-AI workflow around transparency, clinician control, responsible validation, and practical deployment.", alternates: { canonical: "/about" } };

export default function About() {
  return <><PageIntro eyebrow="About Horalix" title="Clinical AI should earn trust through the way it is built." copy="Horalix is developing an echo-first workflow around clinician agency, transparent evidence, and the operational realities of hospital deployment." actions={<Link className="button button-light" href="/contact">Talk with Horalix <Arrow /></Link>} />
    <section className="section shell"><div className="grid-2"><div><p className="eyebrow">Our mission</p><h2>Give echo teams a clearer path from study to review.</h2></div><p className="lede">We believe the best role for AI in echocardiography is to prepare structured, inspectable work while preserving the expertise and final authority of the clinician.</p></div></section>
    <section className="section section-dark" id="team"><div className="shell"><div className="section-heading"><div><p className="eyebrow">The team</p><h2>Names and biographies are published when verified.</h2></div><p className="lede">The production team section will identify company leadership and clinical reviewers with approved titles, biographies, photographs, and profile links. We do not invent credentials to fill a layout.</p></div><div className="metricless-grid"><div className="metricless-card"><b>Product leadership</b><p>Workflow, product strategy, and technical delivery.</p></div><div className="metricless-card"><b>Clinical leadership</b><p>Intended workflow, validation, usability, and safety review.</p></div><div className="metricless-card"><b>Company leadership</b><p>Partnerships, operations, governance, and capital strategy.</p></div></div></div></section>
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Operating principles</p><h2>How we want to build.</h2></div></div><div className="workflow-grid"><article className="workflow-step"><span className="step-no">01 · FOCUS</span><h3>Stay close to the workflow.</h3><p>Build from the real work of echo teams, not a generic story about AI.</p></article><article className="workflow-step"><span className="step-no">02 · SHOW</span><h3>Make evidence traceable.</h3><p>Publish sources, methods, versions, limitations, and review dates together.</p></article><article className="workflow-step"><span className="step-no">03 · RESPECT</span><h3>Preserve clinical agency.</h3><p>Design for inspection, correction, rejection, and final sign-off.</p></article></div></section><SplitCta /></>;
}
