import type { Metadata } from "next";
import Link from "../../_components/ReliableLink";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "../../_components/SiteChrome";
import { getResource, resources } from "../../_data/resources";

export function generateStaticParams() { return resources.map((resource) => ({ slug: resource.slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const resource = getResource(slug); if (!resource) return {};
  return { title: resource.title, description: resource.description, alternates: { canonical: `/resources/${slug}` }, openGraph: { type: "article", siteName: "Horalix", title: resource.title, description: resource.description, url: `https://horalix.com/resources/${slug}`, publishedTime: "2026-08-13", modifiedTime: "2026-08-13", images: [{ url: "/og.png", width: 1200, height: 630, alt: `${resource.title} — Horalix` }] }, twitter: { card: "summary_large_image", title: resource.title, description: resource.description, images: ["/og.png"] } };
}

export default async function ResourceArticle({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const resource = getResource(slug); if (!resource) notFound();
  const authorId = `https://horalix.com/about#${resource.author.id}`;
  const reviewerId = `https://horalix.com/about#${resource.reviewer.id}`;
  const article = { "@context": "https://schema.org", "@graph": [{ "@type": "MedicalWebPage", "@id": `https://horalix.com/resources/${slug}#page`, name: resource.title, url: `https://horalix.com/resources/${slug}`, inLanguage: "en", medicalAudience: { "@type": "MedicalAudience", audienceType: "Clinicians and hospital decision-makers" }, specialty: "https://schema.org/Cardiovascular", dateReviewed: "2026-08-13", reviewedBy: { "@id": reviewerId }, isPartOf: { "@id": "https://horalix.com/#website" } }, { "@type": "Article", headline: resource.title, description: resource.description, inLanguage: "en", datePublished: "2026-08-13", dateModified: "2026-08-13", author: { "@id": authorId }, reviewedBy: { "@id": reviewerId }, publisher: { "@id": "https://horalix.com/#organization" }, citation: resource.sources.map((source) => source.href), mainEntityOfPage: { "@id": `https://horalix.com/resources/${slug}#page` } }, { "@type": "Person", "@id": authorId, name: resource.author.name, jobTitle: resource.author.role, worksFor: { "@id": "https://horalix.com/#organization" }, url: authorId }, { "@type": "Person", "@id": reviewerId, name: resource.reviewer.name, jobTitle: resource.reviewer.role, worksFor: { "@id": "https://horalix.com/#organization" }, url: reviewerId }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Resources", item: "https://horalix.com/resources" }, { "@type": "ListItem", position: 2, name: resource.title, item: `https://horalix.com/resources/${slug}` }] }] };
  return <><article><header className="article-hero"><div className="shell"><Breadcrumbs items={[{ label: "Resources", href: "/resources" }, { label: resource.label }]} /><p className="eyebrow">{resource.label}</p><h1>{resource.title}</h1><p className="lede">{resource.description}</p><div className="article-meta"><span>By <Link href={`/about#${resource.author.id}`}>{resource.author.name}</Link>, {resource.author.role}</span><span>Company review by <Link href={`/about#${resource.reviewer.id}`}>{resource.reviewer.name}</Link>, {resource.reviewer.role}</span><span>Reviewed {resource.reviewed}</span><span>{resource.readTime} read</span></div></div></header><div className="article-body narrow"><div className="answer-box"><strong>Short answer:</strong> {resource.answer}</div>{resource.sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="article-sources"><p className="eyebrow">Primary sources</p>{resource.sources.map((source) => <a href={source.href} key={source.href} rel="noreferrer">{source.title} ↗</a>)}</div><div className="article-related"><p className="eyebrow">Related Horalix context</p>{resource.related.map((item) => <Link href={item.href} key={item.href}>{item.title} <span aria-hidden="true">→</span></Link>)}</div><div className="note-box" style={{ marginTop: 40 }}>This educational resource does not establish Horalix product performance or suitability for a particular clinical environment. <Link href="/evidence">Review the Horalix evidence boundary.</Link></div></div></article><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /></>;
}
