import type { Metadata } from "next";
import Link from "next/link";
import { LeadForm } from "../_components/LeadForm";
import { Arrow, PageIntro } from "../_components/SiteChrome";

export const metadata: Metadata = { title: "For hospitals", description: "Evaluate Horalix with a transparent pilot plan covering echo workflow fit, DICOM integration, clinician oversight, evidence, privacy, and security.", alternates: { canonical: "/for-hospitals" } };

export default function Hospitals() {
  return <>
    <PageIntro eyebrow="For hospitals" title="A clinical-AI pilot should answer the hard questions early." copy="Horalix brings workflow, integration, oversight, security, evidence, and regulatory status into the same pilot conversation." actions={<><a className="button button-light" href="#request">Request hospital demo <Arrow /></a><Link className="button button-ghost" href="/evidence">Review evidence posture</Link></>} />
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Pilot design</p><h2>Start with a bounded clinical workflow.</h2></div><p className="lede">A useful pilot defines eligibility, responsibilities, success criteria, failure paths, data handling, and review ownership before the first study moves.</p></div><div className="timeline"><div className="timeline-row"><b>01 · Discover</b><div><h3>Map the current echo workflow.</h3><p>Identify acquisition systems, routing, reporting destinations, review roles, delays, and operational constraints.</p></div></div><div className="timeline-row"><b>02 · Scope</b><div><h3>Define the pilot boundary.</h3><p>Agree eligible studies, supported views, environment, intended outputs, human oversight, and what the pilot will not establish.</p></div></div><div className="timeline-row"><b>03 · Validate</b><div><h3>Measure more than model output.</h3><p>Evaluate workflow completion, review behavior, integration reliability, exceptions, usability, and agreed evidence measures.</p></div></div><div className="timeline-row"><b>04 · Decide</b><div><h3>Review results with limitations intact.</h3><p>Connect outcomes to the tested version and setting, then decide whether further validation or deployment work is justified.</p></div></div></div></section>
    <section className="section section-dark"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Decision-maker view</p><h2>What your team can inspect.</h2></div><p className="lede">No generic “enterprise-ready” claims. Each requirement is confirmed against the actual pilot environment.</p></div><div className="grid-3"><div className="metricless-card"><b>Clinical operations</b><p>Workflow ownership, review controls, exception handling, and user feedback.</p></div><div className="metricless-card"><b>IT and security</b><p>Architecture, access, routing, data flows, logging, retention, and incident contacts.</p></div><div className="metricless-card"><b>Governance</b><p>Intended use, product status, evidence boundary, responsibilities, and change control.</p></div></div></div></section>
    <section className="section shell" id="request"><div className="form-section"><div><p className="eyebrow">Hospital demo</p><h2>Bring us your real workflow questions.</h2><p className="lede">Tell us who needs to join and what your team wants to evaluate. We will shape the conversation around your hospital—not a generic sales script.</p><p className="microcopy">Business enquiries only. Never submit patient information, DICOM files, or clinical data through this form.</p></div><div className="form-card"><h3>Request a focused hospital demo</h3><p>We’ll respond to arrange a suitable conversation. No patient data is needed.</p><LeadForm intent="hospital_demo" /></div></div></section>
  </>;
}
