import Link from "next/link";
import { Arrow, PageIntro } from "../_components/SiteChrome";
import { claims } from "../_data/claims";
import { pageMetadata } from "../_data/metadata";

export const metadata = pageMetadata({ title: "Clinical AI Evidence & Transparency", description: "Horalix evidence center: product status, claim methodology, human oversight, limitations, internal benchmarks, and clearly separated external research.", path: "/evidence" });

const medicalPage = { "@context": "https://schema.org", "@type": "MedicalWebPage", "@id": "https://horalix.com/evidence#page", name: "Horalix evidence and transparency center", url: "https://horalix.com/evidence", dateReviewed: "2026-08-13", lastReviewed: "2026-08-13", reviewedBy: { "@id": "https://horalix.com/#organization" }, about: { "@id": "https://horalix.com/platform#software" } };

export default function Evidence() {
  const publicClaims = claims.filter((claim) => claim.id !== "program-logos");
  const claimRegister = (
    // This labelled region must be keyboard-focusable so its wide table can be scrolled without a pointer.
    // eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex
    <div className="evidence-table-scroll" role="region" aria-label="Horalix public claim register" tabIndex={0}>
      <table className="evidence-table"><thead><tr><th>Claim area</th><th>Public wording</th><th>Status</th><th>Boundary / disclosure</th><th>Review</th></tr></thead><tbody>{publicClaims.map((claim) => <tr key={claim.id}><td>{claim.classification.replace("-", " ")}</td><td>{claim.status === "approved" ? claim.claim : claim.fallback}</td><td>{claim.status}</td><td>{claim.disclosure}</td><td>{claim.reviewBy}</td></tr>)}</tbody></table>
    </div>
  );
  return <>
    <PageIntro eyebrow="Evidence and transparency" title="Know exactly what has—and has not—been established." copy="Horalix separates product claims, internal benchmarks, field literature, and regulatory status so readers never have to infer the evidence boundary." actions={<><a className="button button-light" href="#claim-register">Open claim register <Arrow /></a><Link className="button button-ghost" href="/resources">Read research resources</Link></>} />
    <section className="section shell"><div className="evidence-status"><article className="status-card"><span className="status">Current product status</span><h3>Pilot-stage and pre-clearance</h3><p>Horalix is being developed and evaluated for pilot workflows. The site does not imply regulatory clearance, routine clinical use, or independent diagnosis.</p></article><article className="status-card"><span className="status">Intended workflow</span><h3>Clinician review and sign-off</h3><p>Suggested outputs are intended to be inspected, adjusted, accepted, or rejected by a qualified clinician before use in a report-ready workflow.</p></article></div></section>
    <section className="section-tight shell" id="claim-register"><div className="section-heading"><div><p className="eyebrow">Public claim register</p><h2>Claims have an owner and an expiry.</h2></div><p className="lede">Unapproved numbers are replaced by non-numeric fallback copy. Approval requires traceable source material and a defined review date.</p></div>{claimRegister}</section>
    <section className="section section-dark"><div className="shell grid-2"><div><p className="eyebrow">Internal benchmarks</p><h2>No isolated headline numbers.</h2><p className="lede">A metric is publishable only with the method needed to interpret it.</p></div><div className="trust-list"><div className="trust-row"><span>Required</span><p>Protocol, sample size, inclusion and exclusion criteria, reference standard, environment, and product version.</p></div><div className="trust-row"><span>Visible</span><p>Limitations, intended interpretation, reviewer, approval date, and next review date.</p></div><div className="trust-row"><span>Current state</span><p>Legacy processing-time and output-count figures remain unpublished pending reconciliation and approval.</p></div></div></div></section>
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">External literature</p><h2>Research that informs our approach—not proof of our product.</h2></div><p className="lede">These sources support principles such as fairness, universality, traceability, usability, robustness, and explainability. They do not validate Horalix.</p></div><div className="source-list"><div className="source-row"><span>Consensus</span><h3>FUTURE-AI: international consensus guideline for trustworthy and deployable artificial intelligence in healthcare</h3><a href="https://www.bmj.com/content/388/bmj-2024-081554" rel="noreferrer">BMJ <Arrow /></a></div><div className="source-row"><span>Systematic review</span><h3>Factors influencing clinician trust in healthcare AI</h3><a href="https://pubmed.ncbi.nlm.nih.gov/40772775/" rel="noreferrer">PubMed <Arrow /></a></div><div className="source-row"><span>Systematic review</span><h3>Explainable AI and trust in medical AI</h3><a href="https://pubmed.ncbi.nlm.nih.gov/39476365/" rel="noreferrer">PubMed <Arrow /></a></div></div><div className="note-box" style={{ marginTop: 42 }}><strong>Evidence boundary:</strong> Citation of external research does not imply that Horalix was evaluated in those studies or has achieved the reported outcomes.</div></section>
    <section className="section-tight shell"><div className="section-heading"><div><p className="eyebrow">Known limitations</p><h2>Limitations belong in the product story.</h2></div></div><div className="metricless-grid"><div className="metricless-card"><b>Compatibility</b><p>DICOM compatibility depends on source systems, study structure, network configuration, and agreed pilot scope.</p></div><div className="metricless-card"><b>Study quality</b><p>Output availability and suitability depend on image quality, view availability, and supported conditions.</p></div><div className="metricless-card"><b>Generalisability</b><p>Pilot findings apply to the tested version, dataset, environment, and workflow—not every hospital or population.</p></div></div></section>
    <section className="section shell section-line"><div className="narrow"><p className="eyebrow">Direct answers</p><h2>What has Horalix not yet demonstrated?</h2><p className="lede">Horalix has not published an approved clinical-performance benchmark, established suitability across every scanner or hospital environment, or claimed clearance for routine clinical use. Those boundaries remain visible until versioned evidence and regulatory documentation support narrower statements.</p><h2>Does external research validate Horalix?</h2><p className="lede">No. External research informs Horalix’s approach to trust, usability, oversight, and deployment. Only studies that evaluate a named Horalix product version in defined conditions can support a Horalix product claim.</p><h2>Who makes the final clinical decision?</h2><p className="lede">The clinician. Horalix is designed to prepare suggestions for inspection, correction, acceptance, or rejection before clinician sign-off.</p></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(medicalPage) }} />
  </>;
}
